spring:
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.250.58:3306/yovv?userSSL=false
    username: ENC(Xv0/Jy4e6216h0hvNxqKCVK5imCjV/9EIlCkMMb6f4LQ9lBfd2tkAe6roJqymY+N)
    password: ENC(Xv0/Jy4e6216h0hvNxqKCVK5imCjV/9EIlCkMMb6f4LQ9lBfd2tkAe6roJqymY+N)
  # session登录态
  session:
    timeout: 84600
server:
  port: 8089
  servlet:
    context-path: /api
  # 解决springboot内嵌tomcat启动ip6
  address: 0.0.0.0

