spring:
  profiles:
    active: dev
  application:
    name: user-center-backend
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/yovvis
#    username: root
#    password: yovvis
    url: jdbc:mysql://111.230.250.58:3306/yovvis
    username: ENC(Xv0/Jy4e6216h0hvNxqKCVK5imCjV/9EIlCkMMb6f4LQ9lBfd2tkAe6roJqymY+N)
    password: ENC(Xv0/Jy4e6216h0hvNxqKCVK5imCjV/9EIlCkMMb6f4LQ9lBfd2tkAe6roJqymY+N)
  # session登录态
  session:
    timeout: 84600
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8089
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
